# Generated by Django 4.1.5 on 2023-01-22 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_pokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
